### ISSUE TITLE
Server Crash (1.7.10)

### ISSUE THREAD

**Issue by Cronosus** [DoubleDoorDevelopment/PlaceableTools#10]
Hello
we have this crash on server, looks randomly, not found cause yet.
http://cronos.wz.cz/mc/crash-2017-07-14_21.57.58-server.txt
Something with bucket?

Server: 1.7.10, thermos b58
mod: PlaceableTools-1.7.10-1.2.0.33

thanks for help

**Comment by Claycorp** [comment]
Not entirely sure whats going on either. Does it happen with just Forge?

Also I doubt this will get fixed as the mod hasn't been worked on in 2 years and 1.12 is around the corner for us.

**Comment by Claycorp** [comment]
No idea either. Can you repeat it with forge only?

Also 1.12 is around the corner for us and this mod hasn't been updated in 2 years, so this might not ever get fixed.

**Comment by Cronosus** [comment]
I found it maybe... someone placed bucket in protected region on spawn.. i think it makes bugged entity, because it not act as object, i see it, but its not there.
this is only crash on my server, nothing else, then i was worried about that.. and will be bad if this repeat in future ;)

**Comment by Cronosus** [comment]
can be this caused, because i use placeable items mod and placeable tools mod together?

**Comment by Claycorp** [comment]
It shows up as a purple icon in NEI because the textures are applied dynamically. No placeable tools and placeable items are fine.

Its likely whatever you are using for protecting spawn causing issues.

**Comment by Cronosus** [comment]
worldguard.. maybe yes

**Comment by Cronosus** [comment]
bad thing is, it causes crashes again and again.. more and more
then i must remove it from my modpack

**Comment by Claycorp** [comment]
That's fine. We can't do anything about it anyway because you use thermos and its not repeatable with vanilla forge.
